version: 2
jobs:
  build:
    docker:
      - image: cimg/node:14.17
    steps:
      - checkout
      - run:
          name: install dependencies
          command: yarn install
      - run:
          name: Run Tests
          command: yarn test