ruby "2.5.3"
source "https://rubygems.org"

group :development, :test do
  # Call `byebug` to stop execution and get a debugger console
  gem "byebug", platforms: [:mri, :mingw, :x64_mingw]
  gem "capybara"
  gem "pry"
  gem "rspec"
  gem "selenium-webdriver"
end
